version: '3.1'
services:
  redis:
    image: redis
  processing:
    build: ./processing
    environment:
      - APP_ENV=prod
  node:
    build: ./api
    environment:
      - APP_ENV=prod
    depends_on:
      - redis
      - processing
